name: verma_classes
version: 1.0.0+1
publish_to: none
description: A new Flutter project for verma classes
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  uuid: ^3.0.5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  path_provider: 2.0.11
  geolocator: ^8.0.5
  get_storage: 2.0.3
  expandable: ^5.0.1
  file_picker: ^4.5.1
  open_file: ^3.2.1
  flutter_downloader: ^1.8.0+1
  intl: ^0.17.0
  share_plus: ^4.0.9
  image_picker: ^0.8.5+3
  clay_containers: ^0.3.2
  pinput: ^2.2.12
  flutter_sticky_header: ^0.6.4


  flutter: 
    sdk: flutter
  badges: ^2.0.3
  webview_flutter: ^3.0.4

dev_dependencies:
  get_cli: any
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/ca/

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/vc_logo.png"

